language: ruby
cache: bundler
rvm:
 - "2.2.3"

addons:
  postgresql: "9.4"

before_script:
  - rake db:init db:create db:migrate
  - phantomjs -v # let's see what Travis has available

script: bin/rspec -f doc
