default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lale_development
  username: postgres
  host: db

test:
  <<: *default
  database: lale_test
  username: postgres
  host: db
