default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lale_development
  <% if ENV["IsDockerContainer"] %>
  username: postgres
  host: db
  <% end %>

test:
  <<: *default
  database: lale_test
  <% if ENV["IsDockerContainer"] %>
  username: postgres
  host: db
  <% end %>
